// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddText: typeof import('./src/components/collapsePanel/src/AddText.vue')['default']
    CollapsePanel: typeof import('./src/components/collapsePanel/CollapsePanel.vue')['default']
    ContCanvas: typeof import('./src/components/lowCode/src/ContCanvas.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FontStyle: typeof import('./src/components/rightModule/src/FontStyle.vue')['default']
    LeftTabs: typeof import('./src/components/leftModule/src/LeftTabs.vue')['default']
    Mapping: typeof import('./src/components/lowCode/src/Mapping.vue')['default']
    RenderBlock: typeof import('./src/components/lowCode/src/RenderBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StyleCompiler: typeof import('./src/components/rightModule/src/StyleCompiler.vue')['default']
    SvgIcon: typeof import('./src/components/common/SvgIcon.vue')['default']
  }
}
