// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddElement: typeof import('./src/components/collapsePanel/src/AddElement.vue')['default']
    AddImage: typeof import('./src/components/collapsePanel/src/AddImage.vue')['default']
    AddText: typeof import('./src/components/collapsePanel/src/AddText.vue')['default']
    AddVideo: typeof import('./src/components/collapsePanel/src/AddVideo.vue')['default']
    ContCanvas: typeof import('./src/components/lowCode/src/ContCanvas.vue')['default']
    Dialog: typeof import('./src/components/dialog/src/Dialog.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FontStyle: typeof import('./src/components/rightModule/src/FontStyle.vue')['default']
    LeftTabs: typeof import('./src/components/leftModule/src/LeftTabs.vue')['default']
    Mapping: typeof import('./src/components/lowCode/src/Mapping.vue')['default']
    PreviewVideo: typeof import('./src/components/dialog/src/PreviewVideo.vue')['default']
    RenderBlock: typeof import('./src/components/lowCode/src/RenderBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowImages: typeof import('./src/components/collapsePanel/src/ShowImages.vue')['default']
    ShowModule: typeof import('./src/components/collapsePanel/src/ShowModule.vue')['default']
    ShowVideo: typeof import('./src/components/dialog/src/ShowVideo.vue')['default']
    ShowVideos: typeof import('./src/components/collapsePanel/src/ShowVideos.vue')['default']
    StyleCompiler: typeof import('./src/components/rightModule/src/StyleCompiler.vue')['default']
    SvgIcon: typeof import('./src/components/common/SvgIcon.vue')['default']
  }
}
